PACKAGE_PREFIX=etherlab-ethercat
PACKAGE_VERSION=1.6.8
DKMS_PACKAGE=$(PACKAGE_PREFIX)-dkms
TOOLS_PACKAGE=$(PACKAGE_PREFIX)-tools

WORKING_DIR=$(shell pwd)
BUILD_PATH=$(WORKING_DIR)/build
PACKAGE_BUILD_PATH=$(BUILD_PATH)/$(PACKAGE_PREFIX)_$(PACKAGE_VERSION)

PACKAGE_SRC_TAR_NAME=ethercat.tar.bz2
PACKAGE_SRC_TAR_PATH=$(PACKAGE_BUILD_PATH)/$(PACKAGE_SRC_TAR_NAME)

DKMS_BUILD_PATH=$(PACKAGE_BUILD_PATH)/$(DKMS_PACKAGE)
DKMS_BUILD_DEBIAN_PATH=$(DKMS_BUILD_PATH)/DEBIAN
DKMS_BUILD_USR_SRC_PATH=$(DKMS_BUILD_PATH)/usr/src/etherlab-ethercat-$(PACKAGE_VERSION)

TOOLS_BUILD_PATH=$(PACKAGE_BUILD_PATH)/$(TOOLS_PACKAGE)

DKMS_DEB_PATH=$(PACKAGE_BUILD_PATH)/$(DKMS_PACKAGE).deb
TOOLS_DEB_PATH=$(PACKAGE_BUILD_PATH)/$(TOOLS_PACKAGE).deb

.PHONY: clean

all: "$(DKMS_DEB_PATH)"

"$(PACKAGE_SRC_TAR_PATH)":
	mkdir -p "$(PACKAGE_BUILD_PATH)";
	wget -O "$(PACKAGE_SRC_TAR_PATH)" https://gitlab.com/etherlab.org/ethercat/-/releases/$(PACKAGE_VERSION)/downloads/dist-tarballs/ethercat.tar.bz2;

"$(DKMS_DEB_PATH)": "$(PACKAGE_SRC_TAR_PATH)"
	mkdir -p "$(DKMS_BUILD_USR_SRC_PATH)";
	tar -xf $(PACKAGE_SRC_TAR_PATH) --strip-components=1 -C "$(DKMS_BUILD_USR_SRC_PATH)";
	sed -e "s/#PACKAGE_VERSION#/$(PACKAGE_VERSION)/" dkms.conf > "$(DKMS_BUILD_USR_SRC_PATH)/dkms.conf";
	mkdir -p "$(DKMS_BUILD_DEBIAN_PATH)"
	sed -e "s/#PACKAGE_VERSION#/$(PACKAGE_VERSION)/" control.dkms > "$(DKMS_BUILD_DEBIAN_PATH)/control";
	sed -e "s/#PACKAGE_VERSION#/$(PACKAGE_VERSION)/" postinst.dkms > "$(DKMS_BUILD_DEBIAN_PATH)/postinst";
	sed -e "s/#PACKAGE_VERSION#/$(PACKAGE_VERSION)/" prerm.dkms > "$(DKMS_BUILD_DEBIAN_PATH)/prerm";
	chmod +x "$(DKMS_BUILD_DEBIAN_PATH)/postinst";
	chmod +x "$(DKMS_BUILD_DEBIAN_PATH)/prerm";
	cd "$(PACKAGE_BUILD_PATH)"; \
	dpkg-deb --build $(DKMS_PACKAGE);

